server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # Ne a SPA indexét adjuk vissza letölthető fájlokhoz
    location ~* \.(rar|zip|7z|exe)$ {
        try_files $uri =404;
    }

    # SPA routing – minden más index.html-re megy
    location / {
        try_files $uri /index.html;
    }
}